name: Nightly E2E Tests Electon Windows
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  e2eTestsElectronWin:
    name: Test Desktop App Windows
    runs-on: windows-latest

    steps:
      - name: Checking out default branch
        uses: actions/checkout@v2
        with:
          ref: develop
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v2
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Running yarn install, prettier and type checks
        run: |
          yarn install --check-files --cache-folder .ycache
          yarn prettier-check
          yarn type-check
      - name: Run Unit tests
        run: yarn test-unit
      - name: Run Electron tests
        run: |
          yarn install-ext
          yarn build-main
          yarn build-e2e
          yarn test-playwright
      - uses: IgnusG/jest-report-action@v2.3.3
        if: always() # Run regardless of whether other steps failed
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          check-name: Report Desktop App Windows
          working-directory: tests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/

#  e2eTestsElectronUbuntu:
#    name: E2E Ubuntu Electron
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v2
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TestData
#        uses: actions/checkout@v2
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build-main
#          yarn build-e2e
#          yarn test-playwright
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-pages
#          path: tests/test-pages/

#  e2eTestsMinioUbuntu:
#    name: E2E Ubuntu Minio
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v2
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TagspacesPro
#        uses: actions/checkout@v2
#        with:
#          repository: tagspaces/tagspacespro
#          token: ${{ secrets.CHECKOUT_TSPRO  }}
#          path: extensions/tagspacespro
#      - name: Checkout TestData
#        uses: actions/checkout@v2
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - uses: suisei-cn/actions-download-file@v1
#        id: minio
#        name: Download the Minio
#        with:
#          url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
#          target: tests/bin/
#      - name: Make the Minio executable
#        run: chmod +x ./tests/bin/minio
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build-main
#          yarn build-e2e
#          yarn test-e2e-electron-minio
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-pages
#          path: tests/test-pages/
#
#  e2eTestsWebUbuntu:
#    name: E2E Ubuntu Web
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v2
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TagspacesPro
#        uses: actions/checkout@v2
#        with:
#          repository: tagspaces/tagspacespro
#          token: ${{ secrets.CHECKOUT_TSPRO  }}
#          path: extensions/tagspacespro
#      - name: Checkout TestData
#        uses: actions/checkout@v2
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - uses: suisei-cn/actions-download-file@v1
#        id: minio
#        name: Download the Minio.exe
#        with:
#          url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
#          target: tests/bin/
#      - name: Make the Minio executable
#        run: chmod +x ./tests/bin/minio
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build-main
#          yarn build-e2e
#          yarn test-e2e-web
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-reports
#          path: tests/test-reports/
